//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AciLabTestApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogin
    {
        public int loginId { get; set; }
        public string StudentName { get; set; }
        public string StudentEmail { get; set; }
        public string Password { get; set; }
    }
}
