//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AciLabTestApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResult
    {
        public int ResId { get; set; }
        public int StudentId { get; set; }
        public string SemesterName { get; set; }
        public string Grade { get; set; }
    }
}
